### ISSUE TITLE
Client-side error since last update

### ISSUE THREAD

**Issue by dotInTheWind** [YunoHost-Apps/crabfit_ynh#8]
Hi,

I just updated the app, and now I'm getting this error message (the usual interface appears for a fraction of a second, before disappearing to display this message).

 `Application error: a client-side exception has occurred (see the browser console for more information).`

Here are the details from the browser console:

```
NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart]
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.sys.mjs:1756
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.sys.mjs:1864
    BG_observe resource:///modules/BrowserGlue.sys.mjs:1086
    _delayedStartup chrome://browser/content/browser.js:2112
BrowserGlue.sys.mjs:1765:15
```
```
update.locale  file doesn't exist in either the application or GRE directories UpdateUtils.sys.mjs:143:13
    getLocale resource://gre/modules/UpdateUtils.sys.mjs:143
```

Thanks!

**Comment by Dazeilad** [comment]
Same issue here...

**Comment by limaanto** [comment]
I cannot reproduce your issue. How did you update or fresh install the package? If the former, could you try uninstalling and reinstalling?

**Comment by Dazeilad** [comment]
Personnaly I am on an almost fresh install of YuNoHost, and I did a fresh install of Crabfit. I tried to uninstall-reinstall the package of course, that didn't solve the issue.

May it be related to a client-side problem instead of a server-side one ? So coming from crabfit itself and not from the YNH package ?

**Comment by agdamsbo** [comment]
I have the same issue here. I am on grabfit version 1.0~ynh4 and tried on Firefox 126.0.1 as well as latest Safari on macos 14.4.1. Exact error as op.

**Comment by gigot-don** [comment]
Hi @limaanto
First: many thanks for your work on this package!

Same issue (sometimes –see under) here, but I may have some leads ;)

## Behavior:
- First installed Crabfit in the first batch of apps on a fresh Yunohost instance; it then worked flawlessly.
- More than a month later, without any manual intervention on the Crabfit app (v. 1.0~ynh4), it displays the same "client-side exception[...]" error message on browser access (Firefox 145.0 and MS Edge 142.0 btw).
- After (too many) reinstallation and rebooting, behavior changes: it now displays "Crab Fit API v3.0.0" as unformatted text in the main browser window.

## What I've found:
- Crabfit is operated *via* two services –that is ofc front- and backend.
- Monitoring the Yunohost admin panel ```[Home] > Tools > Services > crabfit-[front|back]end```, it appears that whenever one of these services is running, the other fails to start *because they try to listen on the same 3000 port*.
- According to several hints, e.g. [the MyNixOS integration](https://mynixos.com/nixpkgs/option/services.crabfit.frontend.port) or even following the source in the Yunohost build, in function ```getPort``` (line 18 of ```/var/www/crabfit/frontend/node_modules/next/dist/lib/utils.js``` found by following the stacktrace –see under) which provides the logic determining the listening port for the frontend, the intended behavior is that backend listens (by default) on port 3000 whereas front listens on 3001.

## Relevant pastes:
### Starting service ```crabfit-frontend``` while ```crabfit-backend``` is running
> crabfit-frontend@2.0.0 start
> next start

> ⨯ Failed to start server
>Error: listen EADDRINUSE: address already in use :::3000
>    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
>    at listenInCluster (node:net:1865:12)
>    at Server.listen (node:net:1953:7)
>    at /var/www/crabfit/frontend/node_modules/next/dist/server/lib/start-server.js:254:16
>    at new Promise (<anonymous>)
>    at startServer (/var/www/crabfit/frontend/node_modules/next/dist/server/lib/start-server.js:191:11)
>    at nextStart (/var/www/crabfit/frontend/node_modules/next/dist/cli/next-start.js:50:40)
>    at /var/www/crabfit/frontend/node_modules/next/dist/bin/next:157:54
>    at async main (/var/www/crabfit/frontend/node_modules/next/dist/bin/next:157:5) {
>  code: 'EADDRINUSE',
>  errno: -98,
>  syscall: 'listen',
>  address: '::',
>  port: 3000
>}
### ```getPort``` function in ```/var/www/crabfit/frontend/node_modules/next/dist/lib/utils.js```
> function getPort(args) {                                              
>    if (typeof args["--port"] === "number") {                         
>        return args["--port"];                                        
>    }                                                                 
>    const parsed = process.env.PORT && parseInt(process.env.PORT, 10);
>    if (typeof parsed === "number" && !Number.isNaN(parsed)) {        
>        return parsed;                                                
>    }                                                                 
>    return 3001;                                                      
>}

I have not yet found where it gets its 3000 from. I would suspect a wild environment variable? but don't take my word for it ;)
